Use latest hashed RDO repository
At the moment, we are using the 'latest' URL which stale cache
can cause problem in the CI.  This will use a hashed URL which
means we'll always get a consistent run.

Depends-On: Id5281e8f3c2453de12d0ec51b58636433e4e8d84
Change-Id: Iab10493c3fb530dcc6de83adf5891a3fec195609

diff --git a/common-tasks/test-set-nodepool-vars.yml b/common-tasks/test-set-nodepool-vars.yml
--- a/common-tasks/test-set-nodepool-vars.yml
+++ b/common-tasks/test-set-nodepool-vars.yml
@@ -32,9 +32,21 @@
         echo "pip_wheel_mirror=${NODEPOOL_WHEEL_MIRROR}"
         echo "centos_epel_mirror=${NODEPOOL_EPEL_MIRROR}"
         echo "galera_percona_xtrabackup_repo_host=${NODEPOOL_PERCONA_PROXY}"
-        echo "openstack_hosts_rdo_mirror_url=${NODEPOOL_RDO_PROXY}"
         echo "galera_repo_host=${NODEPOOL_MIRROR_HOST}:8080"
         echo "repo_build_pip_default_index=${NODEPOOL_PYPI_MIRROR}"
+
+        # NOTE(mnaser): We need to make sure we pull the latest RDO mirror
+        #               which is hashed to avoid cache going stale during CI.
+        # TODO(mnaser): Share this with Puppet
+        #               https://github.com/openstack/puppet-openstack-integration/blob/master/configure_facts.sh#L66-L71
+        export DLRN_BASE=${DLRN_BASE:-centos7-master/puppet-passed-ci}
+        rdo_dlrn=`curl --silent ${NODEPOOL_RDO_PROXY}/${DLRN_BASE}/delorean.repo | grep baseurl | cut -d= -f2`
+        if [[ -z "$rdo_dlrn" ]]; then
+            echo "Failed to parse dlrn hash"
+            exit 1
+        fi
+        RDO_MIRROR_HOST=${rdo_dlrn/https:\/\/trunk.rdoproject.org/$NODEPOOL_RDO_PROXY}
+        echo "openstack_hosts_rdo_repo_url=${RDO_MIRROR_HOST}"
       args:
         executable: /bin/bash
       register: nodepool_variables
